version: '3.9'

services:  

  otto.stock:
    image: lewos/ottostock:latest
    build:
      context: .
      dockerfile: Otto.stock/Dockerfile
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
    ports:
      - "8087:80"
