version: '3.9'

services:  

  otto.stock:
    image: lewos/ottostock:latest
    build:
      context: .
      dockerfile: Otto.stock/Dockerfile
    depends_on:
      - mssql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
    ports:
      - "8087:80"

  otto.stockrequests:
    image: lewos/ottostockrequests:latest
    build:
      context: .
      dockerfile: Otto.stockrequests/Dockerfile
    depends_on:
      - mssql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
    ports:
      - "8086:80"

  otto.products:
    image: lewos/ottoproducts:latest
    build:
      context: .
      dockerfile: Otto.products/Dockerfile
    depends_on:
      - mssql-server
      - otto.m.tokens
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
      URL_OTTO_TOKENS: "http://otto.m.tokens"
      T_USER_AGENT: "(Otto(leo.carmi@gmail.com))"
    ports:
      - "8085:80"

  otto.m.tokens:
    image: lewos/ottomtokens:latest
    build:
      context: .
      dockerfile: Otto.m.tokens/Dockerfile
    depends_on:
      - mssql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
      APP_ID: "744560801851200"
      CLIENT_SECRET: "Bi64oFtxgykxm6HxTct19JY89hty21zp"
    ports:
      - "8084:80"

  otto.orders:
    image: lewos/ottoorders:latest
    build:
      context: .
      dockerfile: Otto.orders/Dockerfile
    depends_on:
      - mssql-server
      - otto.m.tokens
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
      APP_ID: "744560801851200"
      APP_MUSER_ID_OWNER: "302735131"
      T_APP_ID: "5294"
      T_CLIENT_SECRET: "bg5cQxBxlv9fqwtq6b77ewDivPVj85EyAGtWf3M7YysAOBsZ"
      CLIENT_SECRET: "Bi64oFtxgykxm6HxTct19JY89hty21zp"
      REDIRECT_URI: "https://139.144.172.25:8083/api/MOrders"
      URL_OTTO_TOKENS: "http://otto.m.tokens"
      T_USER_AGENT: "(Otto(leo.carmi@gmail.com))"
      PROD_T_ORDERS_URL_WEBHOOK: "https://139.144.172.25:8083/api/TOrders"
      T_ORDERS_URL_WEBHOOK: "https://31a1-190-195-147-188.sa.ngrok.io/api/TOrders"
    ports:
      - "8083:80"
  
  otto.requests:
    image: lewos/ottorequests:latest
    build:
        context: .
        dockerfile: Otto.requests/Dockerfile
    depends_on:
      - mssql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
    ports:
      - "8082:80"

  otto.companies:
    image: lewos/ottocompanies:latest
    build:
      context: .
      dockerfile: Otto.companies/Dockerfile
    depends_on:
      - mssql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
    ports:
      - "8081:80"
  
  otto.users:
    image: lewos/ottousers:latest
    build:
      context: .
      dockerfile: Otto.users/Dockerfile
    depends_on:
      - mssql-server
      - otto.requests
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
      MSSQL_PID: "Express"
      MSSQL_HOST: "mssql-server-new"
      URL_OTTO_REQUESTS: "http://otto.requests"
    ports:
      - "8080:80"
  
  mssql-server:
    container_name: mssql-server-new
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Pa$$w0rd2019"
        MSSQL_PID: "Express"
    volumes:
      - mssql-server-data:/var/opt/mssql/data
    user: root
    ports:
      - "1433:1433"    

volumes:
  mssql-server-data:
